// dashboard/src/constants/featureRanges.js
// Defines the ranges, normalization functions, and metadata for all features used in the wildfire risk dashboard.
// This file centralizes all feature-related constants, making it easy to maintain and update feature definitions in one place.

export const FEATURE_RANGES = {
  centroid_displacement_m:      { min: 0,     max: 2100,   step: 10    },
  centroid_speed_m_per_h:       { min: 0,     max: 600,    step: 5     },
  spread_bearing_deg:           { min: 0,     max: 360,    step: 1     },
  spread_bearing_sin:           { min: -1,    max: 1,      step: 0.001 },
  spread_bearing_cos:           { min: -1,    max: 1,      step: 0.001 },
  area_first_ha:                { min: 0,     max: 12000,  step: 1     },
  log1p_area_first:             { min: 0,     max: 9.4,    step: 0.01  },
  area_growth_abs_0_5h:         { min: 0,     max: 2500,   step: 1     },
  log1p_growth:                 { min: 0,     max: 7.9,    step: 0.01  },
  area_growth_rel_0_5h:         { min: 0,     max: 20,     step: 0.01  },
  relative_growth_0_5h:         { min: 0,     max: 20,     step: 0.01  },
  log_area_ratio_0_5h:          { min: -1,     max: 3.0,    step: 0.01  },
  area_growth_rate_ha_per_h:    { min: 0,     max: 525,    step: 0.5   },
  radial_growth_m:              { min: 0,     max: 1400,   step: 1     },
  radial_growth_rate_m_per_h:   { min: 0,     max: 360,    step: 1     },
  alignment_cos:                { min: -1,    max: 1,      step: 0.01  },
  alignment_abs:                { min: 0,     max: 1,      step: 0.01  },
  cross_track_component:        { min: -220,  max: 280,    step: 1     },
  along_track_speed:            { min: -530,  max: 390,    step: 1     },
  dist_min_ci_0_5h:             { min: 0,     max: 800000, step: 500   },
  dist_std_ci_0_5h:             { min: 0,     max: 900,    step: 10    },
  dist_change_ci_0_5h:          { min: -1800, max: 250,    step: 10    },
  dist_slope_ci_0_5h:           { min: -600,  max: 75,     step: 1     },
  closing_speed_m_per_h:        { min: -55,   max: 360,    step: 1     },
  closing_speed_abs_m_per_h:    { min: 0,     max: 360,    step: 1     },
  projected_advance_m:          { min: -250,  max: 1800,   step: 5     },
  dist_accel_m_per_h2:          { min: -120,  max: 20,     step: 1     },
  dist_fit_r2_0_5h:             { min: 0,     max: 1,      step: 0.01  },
  num_perimeters_0_5h:          { min: 0,     max: 20,     step: 1     },
  dt_first_last_0_5h:           { min: 0,     max: 5,      step: 0.1   },
  low_temporal_resolution_0_5h: { min: 0,     max: 1,      step: 1     },
  event_start_hour:             { min: 0,     max: 23,     step: 1     },
  event_start_dayofweek:        { min: 0,     max: 6,      step: 1     },
  event_start_month:            { min: 1,     max: 12,     step: 1     },
};

export const R = (id) => FEATURE_RANGES[id];

export const ACCENT = "#5B8DD9";

export const THEMES = {
  light: {
    "--color-background-primary":   "#ffffff",
    "--color-background-secondary": "#f5f5f3",
    "--color-background-tertiary":  "#eeede9",
    "--color-text-primary":         "#1a1a18",
    "--color-text-secondary":       "#4a4a46",
    "--color-text-tertiary":        "#888780",
    "--color-border-tertiary":      "rgba(0,0,0,0.10)",
    "--color-border-secondary":     "rgba(0,0,0,0.18)",
    "--font-mono":                  "'Menlo','Consolas',monospace",
  },
  dark: {
    "--color-background-primary":   "#18181b",
    "--color-background-secondary": "#111113",
    "--color-background-tertiary":  "#0c0c0e",
    "--color-text-primary":         "#f0efe8",
    "--color-text-secondary":       "#a8a79f",
    "--color-text-tertiary":        "#636360",
    "--color-border-tertiary":      "rgba(255,255,255,0.08)",
    "--color-border-secondary":     "rgba(255,255,255,0.15)",
    "--font-mono":                  "'Menlo','Consolas',monospace",
  },
};

export const RH_HORIZONS = [
  { key: "prob_12h", label: "12 hours", short: "prob_12h" },
  { key: "prob_24h", label: "24 hours", short: "prob_24h" },
  { key: "prob_48h", label: "48 hours", short: "prob_48h" },
  { key: "prob_72h", label: "72 hours", short: "prob_72h" },
];

// ═══════════════════════════════════════════════════════════════════════════════
// ── CENTROID KINEMATICS features
// ═══════════════════════════════════════════════════════════════════════════════
export const CK_FEATURES = [
  {
    group: 0, id: "centroid_displacement_m", label: "centroid_displacement_m", unit: "m",
    scaleLabels: [R("centroid_displacement_m").min, 
        R("centroid_displacement_m").min+((R("centroid_displacement_m").max - R("centroid_displacement_m").min) / 4), 
        R("centroid_displacement_m").min+2*((R("centroid_displacement_m").max - R("centroid_displacement_m").min) / 4), 
        R("centroid_displacement_m").min+3*((R("centroid_displacement_m").max - R("centroid_displacement_m").min) / 4), 
        R("centroid_displacement_m").max],
    toNorm: (v) => Math.min(v / R("centroid_displacement_m").max, 1),
    meaning: "Total displacement of fire centroid (meters).",
    hint: "Large displacement → fire is moving across terrain, potentially reaching new areas quickly.",
  },
  {
    group: 1, id: "centroid_speed_m_per_h", label: "centroid_speed_m_per_h", unit: "m/h",
    scaleLabels: [R("centroid_speed_m_per_h").min, 
        R("centroid_speed_m_per_h").min+((R("centroid_speed_m_per_h").max - R("centroid_speed_m_per_h").min) / 4), 
        R("centroid_speed_m_per_h").min+2*((R("centroid_speed_m_per_h").max - R("centroid_speed_m_per_h").min) / 4), 
        R("centroid_speed_m_per_h").min+3*((R("centroid_speed_m_per_h").max - R("centroid_speed_m_per_h").min) / 4), 
        R("centroid_speed_m_per_h").max],
    toNorm: (v) => Math.min(v / R("centroid_speed_m_per_h").max, 1),
    meaning: "Speed of centroid movement (meters per hour).",
    hint: "Higher speed → fire front advancing rapidly, reducing reaction time.",
  },
  {
    group: 2, id: "spread_bearing_deg", label: "spread_bearing_deg", unit: "°",
    scaleLabels: [R("spread_bearing_deg").min, 
        R("spread_bearing_deg").min+((R("spread_bearing_deg").max - R("spread_bearing_deg").min) / 4), 
        R("spread_bearing_deg").min+2*((R("spread_bearing_deg").max - R("spread_bearing_deg").min) / 4), 
        R("spread_bearing_deg").min+3*((R("spread_bearing_deg").max - R("spread_bearing_deg").min) / 4), 
        R("spread_bearing_deg").max],
    toNorm: (v) => Math.min(v / R("spread_bearing_deg").max, 1),
    meaning: "Direction of fire spread in degrees (0–360).",
    hint: "Direction alone is not risky unless aligned toward vulnerable zones.",
  },
  {
    group: 2, id: "spread_bearing_sin", label: "spread_bearing_sin", unit: "",
    scaleLabels: [R("spread_bearing_sin").min, 
        R("spread_bearing_sin").min+((R("spread_bearing_sin").max - R("spread_bearing_sin").min) / 4), 
        R("spread_bearing_sin").min+2*((R("spread_bearing_sin").max - R("spread_bearing_sin").min) / 4), 
        R("spread_bearing_sin").min+3*((R("spread_bearing_sin").max - R("spread_bearing_sin").min) / 4), 
        R("spread_bearing_sin").max],
    toNorm: (v) => (v + 1) / 2,
    meaning: "Sine component of spread direction (circular encoding).",
    hint: "Used for modeling direction; not directly indicative of risk.",
  },
  {
    group: 2, id: "spread_bearing_cos", label: "spread_bearing_cos", unit: "",
    scaleLabels: [R("spread_bearing_cos").min, 
        R("spread_bearing_cos").min+((R("spread_bearing_cos").max - R("spread_bearing_cos").min) / 4), 
        R("spread_bearing_cos").min+2*((R("spread_bearing_cos").max - R("spread_bearing_cos").min) / 4), 
        R("spread_bearing_cos").min+3*((R("spread_bearing_cos").max - R("spread_bearing_cos").min) / 4), 
        R("spread_bearing_cos").max],
    toNorm: (v) => (v + 1) / 2,
    meaning: "Cosine component of spread direction (circular encoding).",
    hint: "Used for modeling direction; not directly indicative of risk.",
  },
];

export const CK_GROUPS = [
  { label: "Displacement — spatial reach", dotColor: "#5B8DD9" },
  { label: "Speed — rate of spread",       dotColor: "#5B8DD9" },
  { label: "Bearing & circular encoding",  dotColor: "#5B8DD9" },
];

// ═══════════════════════════════════════════════════════════════════════════════
// ── FIRE GROWTH features
// ═══════════════════════════════════════════════════════════════════════════════
export const FG_FEATURES = [
  {
    group: 0, id: "area_first_ha", label: "area_first_ha", unit: "ha",
    scaleLabels: [R("area_first_ha").min, 
        R("area_first_ha").min+((R("area_first_ha").max - R("area_first_ha").min) / 4), 
        R("area_first_ha").min+2*((R("area_first_ha").max - R("area_first_ha").min) / 4), 
        R("area_first_ha").min+3*((R("area_first_ha").max - R("area_first_ha").min) / 4), 
        R("area_first_ha").max],
    toNorm: (v) => Math.min(v / R("area_first_ha").max, 1),
    meaning: "Initial fire area at t0 (hectares).",
    hint: "Larger initial fire → harder to contain early, higher baseline risk.",
  },
  {
    group: 0, id: "log1p_area_first", label: "log1p_area_first", unit: "",
    scaleLabels: [R("log1p_area_first").min, 
        R("log1p_area_first").min+((R("log1p_area_first").max - R("log1p_area_first").min) / 4), 
        R("log1p_area_first").min+2*((R("log1p_area_first").max - R("log1p_area_first").min) / 4), 
        R("log1p_area_first").min+3*((R("log1p_area_first").max - R("log1p_area_first").min) / 4), 
        R("log1p_area_first").max],
    toNorm: (v) => Math.min(v / R("log1p_area_first").max, 1),
    meaning: "Log-transformed initial fire area.",
    hint: "Encodes fire size while reducing extreme value impact.",
  },
  {
    group: 1, id: "area_growth_abs_0_5h", label: "area_growth_abs_0_5h", unit: "ha",
    scaleLabels: [R("area_growth_abs_0_5h").min, 
        R("area_growth_abs_0_5h").min+((R("area_growth_abs_0_5h").max - R("area_growth_abs_0_5h").min) / 4), 
        R("area_growth_abs_0_5h").min+2*((R("area_growth_abs_0_5h").max - R("area_growth_abs_0_5h").min) / 4), 
        R("area_growth_abs_0_5h").min+3*((R("area_growth_abs_0_5h").max - R("area_growth_abs_0_5h").min) / 4), 
        R("area_growth_abs_0_5h").max],
    toNorm: (v) => Math.min(Math.sqrt(v / R("area_growth_abs_0_5h").max), 1),
    meaning: "Absolute area growth over first 0.5h (hectares).",
    hint: "Fast early expansion → fire is intensifying quickly.",
  },
  {
    group: 1, id: "log1p_growth", label: "log1p_growth", unit: "",
    scaleLabels: [R("log1p_growth").min, 
        R("log1p_growth").min+((R("log1p_growth").max - R("log1p_growth").min) / 4), 
        R("log1p_growth").min+2*((R("log1p_growth").max - R("log1p_growth").min) / 4), 
        R("log1p_growth").min+3*((R("log1p_growth").max - R("log1p_growth").min) / 4), 
        R("log1p_growth").max],
    toNorm: (v) => Math.min(v / R("log1p_growth").max, 1),
    meaning: "Log-transformed absolute area growth.",
    hint: "Captures growth intensity while stabilizing extreme spikes.",
  },
  {
    group: 2, id: "area_growth_rel_0_5h", label: "area_growth_rel_0_5h", unit: "×",
    scaleLabels: [R("area_growth_rel_0_5h").min, 
        R("area_growth_rel_0_5h").min+((R("area_growth_rel_0_5h").max - R("area_growth_rel_0_5h").min) / 4), 
        R("area_growth_rel_0_5h").min+2*((R("area_growth_rel_0_5h").max - R("area_growth_rel_0_5h").min) / 4), 
        R("area_growth_rel_0_5h").min+3*((R("area_growth_rel_0_5h").max - R("area_growth_rel_0_5h").min) / 4), 
        R("area_growth_rel_0_5h").max],
    toNorm: (v) => Math.min(v / R("area_growth_rel_0_5h").max, 1),
    meaning: "Relative area growth over first 0.5h (fraction of initial area).",
    hint: "High relative growth → fire accelerating regardless of initial size.",
  },
  {
    group: 2, id: "relative_growth_0_5h", label: "relative_growth_0_5h", unit: "×",
    scaleLabels: [R("relative_growth_0_5h").min, 
        R("relative_growth_0_5h").min+((R("relative_growth_0_5h").max - R("relative_growth_0_5h").min) / 4), 
        R("relative_growth_0_5h").min+2*((R("relative_growth_0_5h").max - R("relative_growth_0_5h").min) / 4), 
        R("relative_growth_0_5h").min+3*((R("relative_growth_0_5h").max - R("relative_growth_0_5h").min) / 4), 
        R("relative_growth_0_5h").max],
    toNorm: (v) => Math.min(v / R("relative_growth_0_5h").max, 1),
    meaning: "Relative area growth (duplicate of area_growth_rel_0_5h).",
    hint: "Higher values indicate faster proportional expansion.",
  },
  {
    group: 2, id: "log_area_ratio_0_5h", label: "log_area_ratio_0_5h", unit: "",
    scaleLabels: [R("log_area_ratio_0_5h").min, 
        R("log_area_ratio_0_5h").min+((R("log_area_ratio_0_5h").max - R("log_area_ratio_0_5h").min) / 4), 
        R("log_area_ratio_0_5h").min+2*((R("log_area_ratio_0_5h").max - R("log_area_ratio_0_5h").min) / 4), 
        R("log_area_ratio_0_5h").min+3*((R("log_area_ratio_0_5h").max - R("log_area_ratio_0_5h").min) / 4), 
        R("log_area_ratio_0_5h").max],
    toNorm: (v) => Math.min(v / R("log_area_ratio_0_5h").max, 1),
    meaning: "Log ratio of final to initial area over 0.5h.",
    hint: "Higher ratio → explosive relative expansion.",
  },
  {
    group: 3, id: "area_growth_rate_ha_per_h", label: "area_growth_rate_ha_per_h", unit: "ha/h",
    scaleLabels: [R("area_growth_rate_ha_per_h").min, 
        R("area_growth_rate_ha_per_h").min+((R("area_growth_rate_ha_per_h").max - R("area_growth_rate_ha_per_h").min) / 4), 
        R("area_growth_rate_ha_per_h").min+2*((R("area_growth_rate_ha_per_h").max - R("area_growth_rate_ha_per_h").min) / 4), 
        R("area_growth_rate_ha_per_h").min+3*((R("area_growth_rate_ha_per_h").max - R("area_growth_rate_ha_per_h").min) / 4), 
        R("area_growth_rate_ha_per_h").max],
    toNorm: (v) => Math.min(Math.sqrt(v / R("area_growth_rate_ha_per_h").max), 1),
    meaning: "Area growth rate (hectares per hour).",
    hint: "Higher rate → fire spread speed increasing, containment harder.",
  },
  {
    group: 3, id: "radial_growth_m", label: "radial_growth_m", unit: "m",
    scaleLabels: [R("radial_growth_m").min, 
        R("radial_growth_m").min+((R("radial_growth_m").max - R("radial_growth_m").min) / 4), 
        R("radial_growth_m").min+2*((R("radial_growth_m").max - R("radial_growth_m").min) / 4), 
        R("radial_growth_m").min+3*((R("radial_growth_m").max - R("radial_growth_m").min) / 4), 
        R("radial_growth_m").max],
    toNorm: (v) => Math.min(v / R("radial_growth_m").max, 1),
    meaning: "Change in effective fire radius (meters).",
    hint: "Larger radial growth → fire front expanding outward rapidly.",
  },
  {
    group: 3, id: "radial_growth_rate_m_per_h", label: "radial_growth_rate_m_per_h", unit: "m/h",
    scaleLabels: [R("radial_growth_rate_m_per_h").min, 
        R("radial_growth_rate_m_per_h").min+((R("radial_growth_rate_m_per_h").max - R("radial_growth_rate_m_per_h").min) / 4), 
        R("radial_growth_rate_m_per_h").min+2*((R("radial_growth_rate_m_per_h").max - R("radial_growth_rate_m_per_h").min) / 4), 
        R("radial_growth_rate_m_per_h").min+3*((R("radial_growth_rate_m_per_h").max - R("radial_growth_rate_m_per_h").min) / 4), 
        R("radial_growth_rate_m_per_h").max],
    toNorm: (v) => Math.min(v / R("radial_growth_rate_m_per_h").max, 1),
    meaning: "Rate of radial expansion (meters per hour).",
    hint: "High radial speed → fire perimeter advancing quickly toward surroundings.",
  },
];

export const FG_GROUPS = [
  { label: "Group A — absolute growth", dotColor: "#D85A30" },
  { label: "Group B — relative growth", dotColor: "#1D9E75" },
  { label: "Group C — speed & geometry", dotColor: "#378ADD" },
  { label: "Group D — initial state",   dotColor: "#7F77DD" },
];

// ═══════════════════════════════════════════════════════════════════════════════
// ── DIRECTIONALITY features
// ═══════════════════════════════════════════════════════════════════════════════
export const DIR_FEATURES = [
  {
    group: "alignment", id: "alignment_cos", label: "alignment_cos", unit: "",
    scaleLabels: [R("alignment_cos").min, 
        R("alignment_cos").min+((R("alignment_cos").max - R("alignment_cos").min) / 4), 
        R("alignment_cos").min+2*((R("alignment_cos").max - R("alignment_cos").min) / 4), 
        R("alignment_cos").min+3*((R("alignment_cos").max - R("alignment_cos").min) / 4), 
        R("alignment_cos").max],
    toNorm: (v) => (v + 1) / 2,
    meaning: "Cosine of angle between fire motion and evac direction.",
    hint: "Values near +1 → fire moving directly toward evac zones; near -1 → moving away.",
  },
  {
    group: "alignment", id: "alignment_abs", label: "alignment_abs", unit: "",
    scaleLabels: [R("alignment_abs").min, 
        R("alignment_abs").min+((R("alignment_abs").max - R("alignment_abs").min) / 4), 
        R("alignment_abs").min+2*((R("alignment_abs").max - R("alignment_abs").min) / 4), 
        R("alignment_abs").min+3*((R("alignment_abs").max - R("alignment_abs").min) / 4), 
        R("alignment_abs").max],
    toNorm: (v) => v,
    meaning: "Absolute alignment between fire motion and evac direction (0–1).",
    hint: "High alignment means movement is directional, but not necessarily toward evac zones.",
  },
  {
    group: "dynamics", id: "cross_track_component", label: "cross_track", unit: "m/h",
    scaleLabels: [R("cross_track_component").min, 
        R("cross_track_component").min+((R("cross_track_component").max - R("cross_track_component").min) / 4), 
        R("cross_track_component").min+2*((R("cross_track_component").max - R("cross_track_component").min) / 4), 
        R("cross_track_component").min+3*((R("cross_track_component").max - R("cross_track_component").min) / 4), 
        R("cross_track_component").max],
    toNorm: (v) => Math.min(Math.abs(v) / Math.max(Math.abs(R("cross_track_component").min), R("cross_track_component").max), 1),
    meaning: "Sideways drift relative to evac direction (meters/hour).",
    hint: "High sideways drift → fire is not directly approaching evac zones.",
  },
  {
    group: "dynamics", id: "along_track_speed", label: "along_track_speed", unit: "m/h",
    scaleLabels: [R("along_track_speed").min, 
        R("along_track_speed").min+((R("along_track_speed").max - R("along_track_speed").min) / 4), 
        R("along_track_speed").min+2*((R("along_track_speed").max - R("along_track_speed").min) / 4), 
        R("along_track_speed").min+3*((R("along_track_speed").max - R("along_track_speed").min) / 4), 
        R("along_track_speed").max],
    toNorm: (v) => (v - R("along_track_speed").min) / (R("along_track_speed").max - R("along_track_speed").min),
    meaning: "Speed component toward (+) or away (−) from evac zones (meters/hour).",
    hint: "Positive values → fire advancing toward evac zones; negative → retreating.",
  },
];

export const DIR_GROUPS = [
  { id: "alignment", label: "Alignment",        dotColor: "#7F77DD" },
  { id: "dynamics",  label: "Speed components", dotColor: "#D85A30" },
];

// ═══════════════════════════════════════════════════════════════════════════════
// ── RISK SCORE (PROXIMITY) features
// ═══════════════════════════════════════════════════════════════════════════════
export const RS_FEATURES = [
  {
    group: 0, id: "dist_min_ci_0_5h", label: "dist_min_ci_0_5h", unit: "m",
    scaleLabels: [R("dist_min_ci_0_5h").min, 
        R("dist_min_ci_0_5h").min+((R("dist_min_ci_0_5h").max - R("dist_min_ci_0_5h").min) / 4), 
        R("dist_min_ci_0_5h").min+2*((R("dist_min_ci_0_5h").max - R("dist_min_ci_0_5h").min) / 4), 
        R("dist_min_ci_0_5h").min+3*((R("dist_min_ci_0_5h").max - R("dist_min_ci_0_5h").min) / 4), 
        R("dist_min_ci_0_5h").max],
    toNorm: (v) => Math.min(v / R("dist_min_ci_0_5h").max, 1),
    meaning: "Minimum distance to nearest evac zone centroid (meters).",
    hint: "Smaller distance → fire is closer to populated areas, higher immediate risk.",
  },
  {
    group: 0, id: "dist_std_ci_0_5h", label: "dist_std_ci_0_5h", unit: "m",
    scaleLabels: [R("dist_std_ci_0_5h").min, 
        R("dist_std_ci_0_5h").min+((R("dist_std_ci_0_5h").max - R("dist_std_ci_0_5h").min) / 4), 
        R("dist_std_ci_0_5h").min+2*((R("dist_std_ci_0_5h").max - R("dist_std_ci_0_5h").min) / 4), 
        R("dist_std_ci_0_5h").min+3*((R("dist_std_ci_0_5h").max - R("dist_std_ci_0_5h").min) / 4), 
        R("dist_std_ci_0_5h").max],
    toNorm: (v) => Math.min(v / R("dist_std_ci_0_5h").max, 1),
    meaning: "Standard deviation of distances to evac zones.",
    hint: "High variance → uneven proximity; may indicate partial exposure to risk.",
  },
  {
    group: 1, id: "dist_change_ci_0_5h", label: "dist_change_ci_0_5h", unit: "m",
    scaleLabels: [R("dist_change_ci_0_5h").min, 
        R("dist_change_ci_0_5h").min+((R("dist_change_ci_0_5h").max - R("dist_change_ci_0_5h").min) / 4), 
        R("dist_change_ci_0_5h").min+2*((R("dist_change_ci_0_5h").max - R("dist_change_ci_0_5h").min) / 4), 
        R("dist_change_ci_0_5h").min+3*((R("dist_change_ci_0_5h").max - R("dist_change_ci_0_5h").min) / 4), 
        R("dist_change_ci_0_5h").max],
    toNorm: (v) => (v - R("dist_change_ci_0_5h").min) / (R("dist_change_ci_0_5h").max - R("dist_change_ci_0_5h").min),
    meaning: "Change in distance over time (negative = closing in).",
    hint: "Negative change → fire is moving closer to evac zones.",
  },
  {
    group: 1, id: "dist_slope_ci_0_5h", label: "dist_slope_ci_0_5h", unit: "m/h",
    scaleLabels: [R("dist_slope_ci_0_5h").min, 
        R("dist_slope_ci_0_5h").min+((R("dist_slope_ci_0_5h").max - R("dist_slope_ci_0_5h").min) / 4), 
        R("dist_slope_ci_0_5h").min+2*((R("dist_slope_ci_0_5h").max - R("dist_slope_ci_0_5h").min) / 4), 
        R("dist_slope_ci_0_5h").min+3*((R("dist_slope_ci_0_5h").max - R("dist_slope_ci_0_5h").min) / 4), 
        R("dist_slope_ci_0_5h").max],
    toNorm: (v) => (v - R("dist_slope_ci_0_5h").min) / (R("dist_slope_ci_0_5h").max - R("dist_slope_ci_0_5h").min),
    meaning: "Slope of distance vs time (meters/hour).",
    hint: "Negative slope → fire consistently approaching evac zones.",
  },
  {
    group: 1, id: "closing_speed_m_per_h", label: "closing_speed_m_per_h", unit: "m/h",
    scaleLabels: [R("closing_speed_m_per_h").min, 
        R("closing_speed_m_per_h").min+((R("closing_speed_m_per_h").max - R("closing_speed_m_per_h").min) / 4), 
        R("closing_speed_m_per_h").min+2*((R("closing_speed_m_per_h").max - R("closing_speed_m_per_h").min) / 4), 
        R("closing_speed_m_per_h").min+3*((R("closing_speed_m_per_h").max - R("closing_speed_m_per_h").min) / 4), 
        R("closing_speed_m_per_h").max],
    toNorm: (v) => (v - R("closing_speed_m_per_h").min) / (R("closing_speed_m_per_h").max - R("closing_speed_m_per_h").min),
    meaning: "Speed at which fire is closing distance to evac zones (positive = closing).",
    hint: "Higher closing speed → fire approaching rapidly, urgent risk.",
  },
  {
    group: 1, id: "dist_accel_m_per_h2", label: "dist_accel_m_per_h2", unit: "m/h²",
    scaleLabels: [R("dist_accel_m_per_h2").min, 
        R("dist_accel_m_per_h2").min+((R("dist_accel_m_per_h2").max - R("dist_accel_m_per_h2").min) / 4), 
        R("dist_accel_m_per_h2").min+2*((R("dist_accel_m_per_h2").max - R("dist_accel_m_per_h2").min) / 4), 
        R("dist_accel_m_per_h2").min+3*((R("dist_accel_m_per_h2").max - R("dist_accel_m_per_h2").min) / 4), 
        R("dist_accel_m_per_h2").max],
    toNorm: (v) => (v - R("dist_accel_m_per_h2").min) / (R("dist_accel_m_per_h2").max - R("dist_accel_m_per_h2").min),
    meaning: "Acceleration of distance change (meters/hour²).",
    hint: "Negative acceleration → fire is speeding up toward evac zones.",
  },
  {
    group: 2, id: "projected_advance_m", label: "projected_advance_m", unit: "m",
    scaleLabels: [R("projected_advance_m").min, 
        R("projected_advance_m").min+((R("projected_advance_m").max - R("projected_advance_m").min) / 4), 
        R("projected_advance_m").min+2*((R("projected_advance_m").max - R("projected_advance_m").min) / 4), 
        R("projected_advance_m").min+3*((R("projected_advance_m").max - R("projected_advance_m").min) / 4), 
        R("projected_advance_m").max],
    toNorm: (v) => (v - R("projected_advance_m").min) / (R("projected_advance_m").max - R("projected_advance_m").min),
    meaning: "Projected advance toward evac zone (positive = moving closer).",
    hint: "Higher advance → fire likely to reach populated areas soon.",
  },
  {
    group: 2, id: "closing_speed_abs_m_per_h", label: "closing_speed_abs_m_per_h", unit: "m/h",
    scaleLabels: [R("closing_speed_abs_m_per_h").min, 
        R("closing_speed_abs_m_per_h").min+((R("closing_speed_abs_m_per_h").max - R("closing_speed_abs_m_per_h").min) / 4), 
        R("closing_speed_abs_m_per_h").min+2*((R("closing_speed_abs_m_per_h").max - R("closing_speed_abs_m_per_h").min) / 4), 
        R("closing_speed_abs_m_per_h").min+3*((R("closing_speed_abs_m_per_h").max - R("closing_speed_abs_m_per_h").min) / 4), 
        R("closing_speed_abs_m_per_h").max],
    toNorm: (v) => Math.min(v / R("closing_speed_abs_m_per_h").max, 1),
    meaning: "Absolute speed of distance change.",
    hint: "High movement speed, but direction (toward/away) must be considered separately.",
  },
  {
    group: 2, id: "dist_fit_r2_0_5h", label: "dist_fit_r2_0_5h", unit: "",
    scaleLabels: [R("dist_fit_r2_0_5h").min, 
        R("dist_fit_r2_0_5h").min+((R("dist_fit_r2_0_5h").max - R("dist_fit_r2_0_5h").min) / 4), 
        R("dist_fit_r2_0_5h").min+2*((R("dist_fit_r2_0_5h").max - R("dist_fit_r2_0_5h").min) / 4), 
        R("dist_fit_r2_0_5h").min+3*((R("dist_fit_r2_0_5h").max - R("dist_fit_r2_0_5h").min) / 4), 
        R("dist_fit_r2_0_5h").max],
    toNorm: (v) => v,
    meaning: "R² of linear fit to distance vs time.",
    hint: "Higher R² → movement trend is stable and predictable.",
  },
];

export const RS_GROUPS = [
  { label: "Proximity",  dotColor: "#378ADD" },
  { label: "Dynamics",   dotColor: "#5B8DD9" },
  { label: "Projection", dotColor: "#7F77DD" },
];

export const DOW_LABELS   = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
export const MONTH_LABELS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];